inherit_from: .rubocop_todo.yml



# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Style/Lambda:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"
    - "db/schema.rb"